import { execSync } from "node:child_process";
import { after, before, describe } from "node:test";
import { PrismaClient } from "../prisma/client-generated/index.js";
import { PrismaAdapter } from "./polizy.prisma.storage.ts";

import {
  defineStorageAdapterTestSuite,
  type TestObject as SharedTestObject,
  type TestSubject as SharedTestSubject,
  type StorageAdapterTestContext,
} from "./polizy.storage.shared-tests.ts";

const setupTestDatabase = () => {
  try {
    // Ensure the schema (including the unique constraint) is applied. The Prisma
    // client is generated by the package's postinstall hook; rows are cleared
    // between tests via the cleanup hook, so a full reset is unnecessary.
    execSync("pnpm exec prisma db push --skip-generate --accept-data-loss", {
      stdio: "inherit",
    });
  } catch (error) {
    throw new Error(
      "Prisma test DB setup failed. Ensure DATABASE_URL is set and `prisma generate` has run.",
      { cause: error as Error },
    );
  }
};

describe("PrismaStorageAdapter Tests", () => {
  let prisma: PrismaClient;

  before(() => {
    if (!process.env.DATABASE_URL) {
      throw new Error(
        "DATABASE_URL environment variable is not set for testing.",
      );
    }

    prisma = new PrismaClient();
    setupTestDatabase();
  });

  after(async () => {
    await prisma.$disconnect();
  });

  const prismaTestContext: StorageAdapterTestContext = {
    getAdapter: async () => {
      // @ts-ignore
      return PrismaAdapter<SharedTestSubject, SharedTestObject>(prisma);
    },
    cleanup: async () => {
      await prisma.polizyTuple.deleteMany({});
    },
  };

  defineStorageAdapterTestSuite("PrismaStorageAdapter", prismaTestContext);
});
